[build]
  publish = "."

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/logos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/projects/*"
  to = "/projects/:splat.html"
  status = 200

[[redirects]]
  from = "/products/*"
  to = "/products/:splat.html"
  status = 200

[[redirects]]
  from = "/journal/*"
  to = "/journal/:splat.html"
  status = 200
